// <auto-generated />
using M13Demo_EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M13Demo_EntityFramework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20200528123547_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("M13Demo_EntityFramework.Models.Akkuschrauber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AkkuTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preis")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DieAkkuschrauber");
                });
#pragma warning restore 612, 618
        }
    }
}
